# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com/nice-cxone
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_ACCESS_TOKEN}}
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "10:02"
      timezone: "UTC"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
        # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
