version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
       - "9411:9411"
  admin-service:
    build:
      context: admin
      dockerfile: Dockerfile
    image: admin-server:latest
    ports:
      - "8080:8080"
#  aggregation-service:
#    build:
#      context: aggregation-service
#      dockerfile: Dockerfile
#    image: aggregation-server:latest
#    ports:
#      - "8081:8081" # for scaling-services https://www.baeldung.com/dockerizing-spring-boot-application#3-scaling-services
  converter-service:
    build:
      context: converter-service
      dockerfile: Dockerfile
    image: converter-server:latest
    ports:
      - "9091:9091"
    environment:
      - "SPRING_PROFILES_ACTIVE=integration-tests"
