version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
       - "9411:9411"
  admin-server:
    build:
      context: admin
      dockerfile: Dockerfile
    image: admin-server:latest
    ports:
      - "8080:8080"
  aggregation-service:
    build:
      context: aggregation-service
      dockerfile: Dockerfile
    image: aggregation-server:latest
    depends_on:
      - zipkin
      - admin-server
      - converter-service
    ports:
      - "8081:8081" # for scaling-services https://www.baeldung.com/dockerizing-spring-boot-application#3-scaling-services
    environment:
      - "SPRING_PROFILES_ACTIVE=integration-tests"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans"
  converter-service:
    build:
      context: converter-service
      dockerfile: Dockerfile
    image: converter-server:latest
    depends_on:
      - zipkin
      - admin-server
    ports:
      - "9091:9091"
    environment:
      - "SPRING_PROFILES_ACTIVE=integration-tests"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans"
