version: "3.9"
services:
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - "9411:9411"
    networks:
      - my-network
  admin-server:
    build:
      context: admin
      dockerfile: Dockerfile
    image: admin-server:latest
    ports:
      - "8085:8085"
    networks:
      - my-network
  converter-service:
    build:
      context: converter-service
      dockerfile: Dockerfile
    image: converter-server:latest
    depends_on:
      - zipkin-server
      - admin-server
      - gateway
      - eureka-server
    ports:
      - "9091:9091"
    networks:
      - my-network
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans"
  aggregation-service:
    build:
      context: aggregation-service
      dockerfile: Dockerfile
    image: aggregation-server:latest
    depends_on:
      - zipkin-server
      - admin-server
      - gateway
      - eureka-server
#      - converter-service
    ports:
      - "8081:8081" # for scaling-services https://www.baeldung.com/dockerizing-spring-boot-application#3-scaling-services
    networks:
      - my-network
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans"
  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - my-network
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    image: gateway:latest
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
networks:
  my-network: