server:
  port: 8081
writer-class-name: ConsoleWriter

spring:
  application:
    name: aggregation-service
  boot:
    admin:
      client:
        url: http://localhost:8080
#        instance:
#          service-base-url: http://localhost:8081
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
#        username: admin
#        password: admin
#  security:
#    user:
#      name: client
#      password: client
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"