server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: converter-route
          uri: lb://converter-service # route according to register in Eureka Server
          predicates:
            - Path=/convert/**
        - id: aggregation-route
          uri: lb://aggregation-service
          predicates:
            - Path=/aggregation/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # אופציונלי: כדי לראות לוגים של Gateway
