server:
  port: 9091
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  boot:
    admin:
      client:
        url: "http://localhost:8080"
        instance:
          service-base-url: "http://localhost:${server.port}"
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
#        username: admin
#        password: admin
#  security:
#    user:
#      name: client
#      password: client
management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

aggregation:
  server:
    base-url: "http://localhost:"
    port: 8081
  url: /aggregate/
scheduler:
  sendEveryPeriodTimeInMillis: 5000

